name: Pull Request Workflow

on:
  push:
    branches:
      - master

jobs:
  create-review-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config credential.helper '!f() { echo "password=$GH_TOKEN"; }; f'
      - name: Create 'to-review' Branch
        run: |
          git checkout -b to-review
          git push origin to-review

  create-pull-request:
    runs-on: ubuntu-latest
    needs: create-review-branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          gh pr create --base master --head to-review --title "Review Request" --body "Hey @dominikstas, there's a new push for review."

  notify-for-review:
    runs-on: ubuntu-latest
    needs: create-pull-request
    steps:
      - name: Notify for Review
        run: echo "Pull Request created for review. @dominikstas, please review it."

  merge-to-master:
    runs-on: ubuntu-latest
    needs: notify-for-review
    steps:
      - name: Merge 'to-review' into 'master'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout master
          git merge --no-ff to-review
          git push origin master
