#basic workflow for OPIUM

name: Pull Request Workflow

on:
  push:
    branches:
      - master

jobs:
  create-review-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo "machine github.com login dominikstas password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          
      - name: Create 'to-review' Branch
        run: |
          git checkout -b to-review
          git push origin to-review


  notify-for-review:
    runs-on: ubuntu-latest
    needs: create-review-branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Notify for Review
        run: echo "@dominikstas there's a new push for review " 

  merge-to-master:
    runs-on: ubuntu-latest
    needs: notify-for-review
    steps:
      - name: Checkout 'master' Branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Merge 'to-review' into 'master'
        run: |
          git merge --no-ff to-review
          git push origin master

